name: Release Please
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: elixir
          package-name: crono
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
